// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handler/argsvalidator/argsvalidator.go
//
// Generated by this command:
//
//	mockgen -source=internal/handler/argsvalidator/argsvalidator.go -destination=internal/handler/argsvalidator/mocks/mocks.go -package=mocks ArgsValidator
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	argsvalidator "github.com/jne100/golang-service-layout/internal/handler/argsvalidator"
	gomock "go.uber.org/mock/gomock"
)

// MockArgsValidator is a mock of ArgsValidator interface.
type MockArgsValidator struct {
	ctrl     *gomock.Controller
	recorder *MockArgsValidatorMockRecorder
	isgomock struct{}
}

// MockArgsValidatorMockRecorder is the mock recorder for MockArgsValidator.
type MockArgsValidatorMockRecorder struct {
	mock *MockArgsValidator
}

// NewMockArgsValidator creates a new mock instance.
func NewMockArgsValidator(ctrl *gomock.Controller) *MockArgsValidator {
	mock := &MockArgsValidator{ctrl: ctrl}
	mock.recorder = &MockArgsValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArgsValidator) EXPECT() *MockArgsValidatorMockRecorder {
	return m.recorder
}

// PositiveInt32 mocks base method.
func (m *MockArgsValidator) PositiveInt32(x int32) argsvalidator.ArgValidator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PositiveInt32", x)
	ret0, _ := ret[0].(argsvalidator.ArgValidator)
	return ret0
}

// PositiveInt32 indicates an expected call of PositiveInt32.
func (mr *MockArgsValidatorMockRecorder) PositiveInt32(x any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PositiveInt32", reflect.TypeOf((*MockArgsValidator)(nil).PositiveInt32), x)
}

// SaneItemName mocks base method.
func (m *MockArgsValidator) SaneItemName(name string) argsvalidator.ArgValidator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaneItemName", name)
	ret0, _ := ret[0].(argsvalidator.ArgValidator)
	return ret0
}

// SaneItemName indicates an expected call of SaneItemName.
func (mr *MockArgsValidatorMockRecorder) SaneItemName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaneItemName", reflect.TypeOf((*MockArgsValidator)(nil).SaneItemName), name)
}

// SaneSKU mocks base method.
func (m *MockArgsValidator) SaneSKU(id string) argsvalidator.ArgValidator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaneSKU", id)
	ret0, _ := ret[0].(argsvalidator.ArgValidator)
	return ret0
}

// SaneSKU indicates an expected call of SaneSKU.
func (mr *MockArgsValidatorMockRecorder) SaneSKU(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaneSKU", reflect.TypeOf((*MockArgsValidator)(nil).SaneSKU), id)
}

// Validate mocks base method.
func (m *MockArgsValidator) Validate(ctx context.Context, validators ...argsvalidator.ArgValidator) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range validators {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Validate", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockArgsValidatorMockRecorder) Validate(ctx any, validators ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, validators...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockArgsValidator)(nil).Validate), varargs...)
}
