"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Item(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SKU_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    QUANTITY_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    sku: builtins.str
    name: builtins.str
    quantity: builtins.int
    @property
    def created_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        sku: builtins.str = ...,
        name: builtins.str = ...,
        quantity: builtins.int = ...,
        created_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["created_at", b"created_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["created_at", b"created_at", "name", b"name", "quantity", b"quantity", "sku", b"sku"]) -> None: ...

global___Item = Item

@typing.final
class CreateItemRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ITEM_FIELD_NUMBER: builtins.int
    @property
    def item(self) -> global___Item: ...
    def __init__(
        self,
        *,
        item: global___Item | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["item", b"item"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["item", b"item"]) -> None: ...

global___CreateItemRequest = CreateItemRequest

@typing.final
class CreateItemResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___CreateItemResponse = CreateItemResponse

@typing.final
class GetItemRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SKU_FIELD_NUMBER: builtins.int
    sku: builtins.str
    def __init__(
        self,
        *,
        sku: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["sku", b"sku"]) -> None: ...

global___GetItemRequest = GetItemRequest

@typing.final
class GetItemResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ITEM_FIELD_NUMBER: builtins.int
    @property
    def item(self) -> global___Item: ...
    def __init__(
        self,
        *,
        item: global___Item | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["item", b"item"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["item", b"item"]) -> None: ...

global___GetItemResponse = GetItemResponse
