# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\x0cinventory.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"c\n\x04Item\x12\x0b\n\x03sku\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12.\n\ncreated_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"5\n\x11\x43reateItemRequest\x12 \n\x04item\x18\x01 \x01(\x0b\x32\x12.inventory.v1.Item\"\x14\n\x12\x43reateItemResponse\"\x1d\n\x0eGetItemRequest\x12\x0b\n\x03sku\x18\x01 \x01(\t\"3\n\x0fGetItemResponse\x12 \n\x04item\x18\x01 \x01(\x0b\x32\x12.inventory.v1.Item2\xab\x01\n\x10InventoryService\x12O\n\nCreateItem\x12\x1f.inventory.v1.CreateItemRequest\x1a .inventory.v1.CreateItemResponse\x12\x46\n\x07GetItem\x12\x1c.inventory.v1.GetItemRequest\x1a\x1d.inventory.v1.GetItemResponseB-Z+github.com/jne100/golang-service-layout/apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/jne100/golang-service-layout/api'
  _globals['_ITEM']._serialized_start=66
  _globals['_ITEM']._serialized_end=165
  _globals['_CREATEITEMREQUEST']._serialized_start=167
  _globals['_CREATEITEMREQUEST']._serialized_end=220
  _globals['_CREATEITEMRESPONSE']._serialized_start=222
  _globals['_CREATEITEMRESPONSE']._serialized_end=242
  _globals['_GETITEMREQUEST']._serialized_start=244
  _globals['_GETITEMREQUEST']._serialized_end=273
  _globals['_GETITEMRESPONSE']._serialized_start=275
  _globals['_GETITEMRESPONSE']._serialized_end=326
  _globals['_INVENTORYSERVICE']._serialized_start=329
  _globals['_INVENTORYSERVICE']._serialized_end=500
# @@protoc_insertion_point(module_scope)
